#!/usr/bin/env bash

_main() {
	local arg_name="$1"
	APP_POPOVER=0

	_log() {
		local arg_prefix="$1"
		local arg_prefix_color="$2"
		local arg_msg_color="$3"
		local arg_msg="$4"
		local line="${5:-$LINENO}"
		local no_color='\033[0m'
		local script="${0##*/}"

		echo -e "${arg_prefix_color}${arg_prefix}: \
			${no_color} ${msg_color}${arg_msg}${no_color}" >&2
		echo -e "  ---> ${script}:${line}${no_color}" >&2
	}

	warn() {
		local arg_msg="$1"
		local line="${2:-$LINENO}"
		local yellow='\033[0;33m'
		local bold_yellow='\033[1;33m'

		_log "WARNING" "$bold_yellow" "$yellow" "$arg_msg" "$line"
	}

	err() {
		local arg_msg="$1"
		local line="${2:-$LINENO}"
		local red='\033[0;31m'
		local bold_red='\033[1;31m'

		_log "ERROR" "$bold_red" "$red" "$arg_msg" "$line"
	}

	get_proj_dir() {
		echo "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
	}

	_using() {
		local arg_name="$1"
		local file="$(get_proj_dir)/$arg_name.sh"

		if [[ ! -f "$file" ]]; then
			err "Sourcing non-existent file '$file'."

			exit 1
		fi

		source "$file"
	}

	using_util() { _using "util"; }

	using_config() { _using "config"; }

	local mode_file="$(get_proj_dir)/$arg_name.sh"

	if [[ ! -f "$mode_file" ]]; then
		err "Invalid arg '$arg_name'."

		exit 1
	fi

	source "$mode_file"
}

_main "$1"
